### PR TITLE
New Coordinate Classes

### PR DESCRIPTION
**Pull request by BatchelorJ**
This PR adds the following features:

- New classes for coordinates in the form of Cartesian, Geographic and Transverse Mercator
- New class methods to allow for easy coordinate conversion between these types
- Ability to change angular notation for Geographic Coordinates

These features will allow for the following future developments:

- Simplified Helmert Transformation of coordinates in Geographic and Transverse Mercator form (enable Conform7 and Conform14 to take and return coord classes without converting first)
- Standardised Coordinate Uncertainty added to coord classes as an optional attribute, simplified interaction with TransformationSD

### CODE REVIEW

**Comment by BatchelorJ** [comment]
If it's possible, I'd be interested to hear any feedback from @nicgowans before merging too.

**Review by nicgowans — COMMENTED** [review]
Nice work, Josh!

This is a great direction to be heading in.

May I suggest the following changes in `coord.py`:
- lines 122 and 286: change difference to different
- lines 127 and 130: swap the latitude/longitude angular extents [+/-90 vs 180]
- line 248: correct the geoid separation calc to `self.ell_ht - self.orth_ht`


There a few things worth considering in the long-term as well:

- Introduction of coordinate uncertainties (as you note) whether as SDs or a variance matrix
- Coordinate metadata, such as reference frame and epoch of expression.
- Expanding the geoid separation component to be independent from the `nval = ell_ht - ortho_ht` relationship. When we discussed earlier, we agreed geoid separation could be derived as you've done here, but having had more time to think about this I see there's an advantage in allowing for imperfections in realisations of vertical reference systems and geoid models, e.g. GDA heights, AHD heights and AUSGeoid nvals often don't sum to zero. Along these lines, a geoid_model metadata field could also provide traceability for a given geoid separation.

**Comment by BatchelorJ** [comment]
Thanks very much @nicgowans for your comments and feedback. I have implemented the changes you suggested and additionally resolved another couple of bugs in the Ellipsoid/Orthometric/N Value relationships and test data, specifically:
- Line 102: changed Orthometric Height comp from `ell_ht + nval` to `ell_ht - nval`
- Changed test_coord cartesian example 1 N Value sign to reflect correct mathematical relationship between Ellipsoid/Orthometric/N Value.

Thanks also for the suggestions of where this development could go long-term. Those are all great suggestions that I think warrant further discussion and exploration of the best way to integrate them into the package.

**Comment by harry093** [comment]
@BatchelorJ sorry mate, got some NGCA issues to sort and then I'll have a look at this

**Review by harry093 — APPROVED** [review]
@BatchelorJ This is excellent! I like the forward planning from both you and @nicgowans.

**Pull request merged**
